const LOGGED_IN = "LOGGED_IN"
const SET_STACK ="SET_STACK"
const SET_AGE_HEIGHT_WEIGHT="SET_AGE_HEIGHT_WEIGHT"
const SET_WORKOUT_TIME = "SET_WORKOUT_TIME"
const SET_GOAL = "SET_GOAL"
const SET_GOAL_WEIGHT_TIME = "SET_GOAL_WEIGHT_TIME"
const DIETRY_PREFERENCES ="DIETRY_PREFERENCES"
const SET_FAVORITE_CUISINES ="SET_FAVORITE_CUISINES"
const SET_THINGS_TO_AVOID ="SET_THINGS_TO_AVOID"
const SET_MORE_THINGS_TO_AVOID = "SET_MORE_THINGS_TO_AVOID"
const SET_MICRO_NUTRIENTS = "SET_MICRO_NUTRIENTS"
const SET_SCHEDULE ="SET_SCHEDULE"
const SET_TIME_IN_KITCHEN ="SET_TIME_IN_KITCHEN"
const SET_BUDGET ="SET_BUDGET"
const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN"
const SET_USER_SIGNED_IN = "SET_USER_SIGNED_IN"
const SET_ACCOUNT_TYPE = "SET_ACCOUNT_TYPE"

/// traing user functions
const SET_TRAIN_USER_SIGNED_IN = "SET_TRAIN_USER_SIGNED_IN"
const SET_TRAIN_AGE_HEIGHT_WEIGHT = "SET_TRAIN_AGE_HEIGHT_WEIGHT"
const SET_TRAIN_USER_LOGGED_IN = "SET_TRAIN_USER_LOGGED_IN"
const SET_TRAIN_WORK_OUT = "SET_TRAIN_WORK_OUT"
const SET_TRAIN_FINAL_GOAL = "SET_TRAIN_FINAL_GOAL"
const SET_TRAIN_ESTIMATED_TARGET_DATE = "SET_TRAIN_ESTIMATED_TARGET_DATE"
const SET_TRAIN_TIME_SPENT_EXERCISING = "SET_TRAIN_TIME_SPENT_EXERCISING"
const SET_TRAIN_WORKOUT_PLACE = "SET_TRAIN_WORKOUT_PLACE"
const SET_TRAIN_IS_CURRENTLY_DOING_SPORTS = "SET_TRAIN_IS_CURRENTLY_DOING_SPORTS"
const SET_TRAIN_SPORTS_NAME ="SET_TRAIN_SPORTS_NAME"
const SET_TRAIN_SPORTS_TIME = "SET_TRAIN_SPORTS_TIME"
const SET_TRAIN_IS_TRUSTS = "SET_TRAIN_IS_TRUSTS"
const SET_TRAIN_PREFERRED_WORKOUT  ="SET_TRAIN_PREFERRED_WORKOUT"
const SET_TRAIN_PREFERRED_WORKOUT_AVOID = "SET_TRAIN_PREFERRED_WORKOUT_AVOID"
const SET_TRAIN_EQUIPMENTS = "SET_TRAIN_EQUIPMENTS"
const SET_TRAIN_EXERCISE = "SET_TRAIN_EXERCISE"
const SET_TRAIN_WORKOUT_DAYS = "SET_TRAIN_WORKOUT_DAYS"


const ADD_WEIGHT = "ADD_WEIGHT"
const DELETE_WEIGHT = "DELETE_WEIGHT"
export {
    LOGGED_IN,
    SET_STACK,
    SET_AGE_HEIGHT_WEIGHT,
    SET_WORKOUT_TIME,
    SET_GOAL,
    DIETRY_PREFERENCES,
    SET_GOAL_WEIGHT_TIME,
    SET_FAVORITE_CUISINES,
    SET_THINGS_TO_AVOID,
    SET_MORE_THINGS_TO_AVOID,
    SET_MICRO_NUTRIENTS,
    SET_SCHEDULE,
    SET_TIME_IN_KITCHEN,
    SET_BUDGET,
    SET_USER_LOGGED_IN,
    SET_USER_SIGNED_IN,
    SET_ACCOUNT_TYPE,
    SET_TRAIN_USER_SIGNED_IN,
    SET_TRAIN_AGE_HEIGHT_WEIGHT,
    SET_TRAIN_USER_LOGGED_IN,
    SET_TRAIN_WORK_OUT,
    SET_TRAIN_FINAL_GOAL,
    SET_TRAIN_ESTIMATED_TARGET_DATE,
    SET_TRAIN_TIME_SPENT_EXERCISING,
    SET_TRAIN_WORKOUT_PLACE,
    SET_TRAIN_IS_CURRENTLY_DOING_SPORTS,
    SET_TRAIN_SPORTS_NAME,
    SET_TRAIN_SPORTS_TIME,
    SET_TRAIN_IS_TRUSTS,
    SET_TRAIN_PREFERRED_WORKOUT,
    SET_TRAIN_PREFERRED_WORKOUT_AVOID,
    SET_TRAIN_EQUIPMENTS,
    SET_TRAIN_EXERCISE,
    SET_TRAIN_WORKOUT_DAYS,
    DELETE_WEIGHT,
    ADD_WEIGHT

};