const LOGGED_IN = "LOGGED_IN"
const SET_STACK ="SET_STACK"
const SET_AGE_HEIGHT_WEIGHT="SET_AGE_HEIGHT_WEIGHT"
const SET_WORKOUT_TIME = "SET_WORKOUT_TIME"
const SET_GOAL = "SET_GOAL"
const SET_GOAL_WEIGHT_TIME = "SET_GOAL_WEIGHT_TIME"
const DIETRY_PREFERENCES ="DIETRY_PREFERENCES"
const SET_FAVORITE_CUISINES ="SET_FAVORITE_CUISINES"
const SET_THINGS_TO_AVOID ="SET_THINGS_TO_AVOID"
const SET_MORE_THINGS_TO_AVOID = "SET_MORE_THINGS_TO_AVOID"
const SET_MICRO_NUTRIENTS = "SET_MICRO_NUTRIENTS"
const SET_SCHEDULE ="SET_SCHEDULE"
const SET_TIME_IN_KITCHEN ="SET_TIME_IN_KITCHEN"
const SET_BUDGET ="SET_BUDGET"
export {
    LOGGED_IN,
    SET_STACK,
    SET_AGE_HEIGHT_WEIGHT,
    SET_WORKOUT_TIME,
    SET_GOAL,
    DIETRY_PREFERENCES,
    SET_GOAL_WEIGHT_TIME,
    SET_FAVORITE_CUISINES,
    SET_THINGS_TO_AVOID,
    SET_MORE_THINGS_TO_AVOID,
    SET_MICRO_NUTRIENTS,
    SET_SCHEDULE,
    SET_TIME_IN_KITCHEN,
    SET_BUDGET
};